-- =====================================================================
-- V11: Títulos de sección de la web, configurables desde el panel.
--
-- OJO con el nombre de la columna: la primera versión de esta migración usaba
-- `leading`, que es una PALABRA RESERVADA de PostgreSQL (aparece en
-- TRIM(LEADING ...)). Sin comillas provoca `syntax error at or near "leading"`,
-- la migración falla y —al ejecutar Flyway durante el arranque— la API entera
-- no levanta. Se renombra a `leading_text` en lugar de citarla: una columna que
-- necesita comillas en cada consulta es una trampa permanente.
-- =====================================================================

CREATE TABLE IF NOT EXISTS section_title (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    section_key  VARCHAR(50)  NOT NULL,
    leading_text VARCHAR(100) NOT NULL,
    highlight    VARCHAR(100) NOT NULL,
    accent       VARCHAR(20)  NOT NULL DEFAULT 'gold',
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_section_title PRIMARY KEY (id),
    CONSTRAINT uq_section_title_key UNIQUE (section_key)
);

INSERT INTO section_title (section_key, leading_text, highlight, accent, active)
SELECT * FROM (VALUES
    ('menu',      'Nuestra',  'Carta',  'gold',  TRUE),
    ('videos',    'Nuestros', 'Videos', 'red',   TRUE),
    ('locations', 'Nuestras', 'Sedes',  'amber', TRUE)
) AS seed(section_key, leading_text, highlight, accent, active)
WHERE NOT EXISTS (SELECT 1 FROM section_title);
