-- V12: Sugerencias de prompt para el asistente de IA y el recomendador
CREATE TABLE IF NOT EXISTS ai_suggestion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(20) NOT NULL,
    prompt_text VARCHAR(255) NOT NULL,
    order_index INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ai_suggestion (kind, prompt_text, order_index, active) VALUES
('chat', '¿Qué hamburguesa me recomiendas?', 1, true),
('chat', '¿Cuáles son sus horarios?', 2, true),
('chat', '¿Dónde están ubicados?', 3, true),
('chat', '¿Cómo pago con Yape?', 4, true),
('recommender', 'Algo con harto queso', 1, true),
('recommender', 'Picante y contundente', 2, true),
('recommender', 'Lo más barato que tengan', 3, true),
('recommender', 'Para compartir entre dos', 4, true);
