-- =====================================================================
-- La Bumanguesa - initial schema (ANSI SQL / PostgreSQL & SQL Server 2022+)
-- Mirrors the content contracts defined by the Angular frontend.
-- =====================================================================

CREATE TABLE site_setting (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand                     VARCHAR(80)   NOT NULL,
    city                      VARCHAR(80)   NOT NULL,
    country                   VARCHAR(80)   NOT NULL,
    whatsapp_number           VARCHAR(15)   NOT NULL,
    whatsapp_display          VARCHAR(40)   NOT NULL,
    default_order_message     VARCHAR(500)  NOT NULL,
    show_promo_bar            BOOLEAN       NOT NULL DEFAULT TRUE,
    facebook_url              VARCHAR(500)  NOT NULL,
    instagram_url             VARCHAR(500)  NOT NULL,
    tiktok_url                VARCHAR(500)  NOT NULL,
    hours_weekdays            VARCHAR(60)   NOT NULL,
    hours_weekend             VARCHAR(60)   NOT NULL,
    copyright_year            INT            NOT NULL,
    marquee_text              VARCHAR(500)  NOT NULL,
    marquee_duration_seconds  INT            NOT NULL,
    created_at                TIMESTAMP      NOT NULL,
    updated_at                TIMESTAMP      NOT NULL,
    CONSTRAINT pk_site_setting PRIMARY KEY (id)
);

CREATE TABLE menu_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slug            VARCHAR(80)  NOT NULL,
    title           VARCHAR(120) NOT NULL,
    description     VARCHAR(500) NOT NULL,
    image_url       VARCHAR(500) NOT NULL,
    badge           VARCHAR(60)  NOT NULL,
    badge_rotation  INT           NOT NULL,
    accent          VARCHAR(10)  NOT NULL,
    cta_label       VARCHAR(60)  NOT NULL,
    order_index     INT           NOT NULL DEFAULT 0,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL,
    CONSTRAINT pk_menu_item PRIMARY KEY (id),
    CONSTRAINT uq_menu_item_slug UNIQUE (slug)
);

CREATE TABLE video (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slug           VARCHAR(80)  NOT NULL,
    platform       VARCHAR(20)  NOT NULL,
    label          VARCHAR(40)  NOT NULL,
    thumbnail_url  VARCHAR(500) NOT NULL,
    accent_color   VARCHAR(30)  NOT NULL,
    offset_y       INT           NOT NULL DEFAULT 0,
    url            VARCHAR(500) NOT NULL,
    order_index    INT           NOT NULL DEFAULT 0,
    active         BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP     NOT NULL,
    updated_at     TIMESTAMP     NOT NULL,
    CONSTRAINT pk_video PRIMARY KEY (id),
    CONSTRAINT uq_video_slug UNIQUE (slug)
);

CREATE TABLE location (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    slug           VARCHAR(80)   NOT NULL,
    name           VARCHAR(120)  NOT NULL,
    address        VARCHAR(200)  NOT NULL,
    accent         VARCHAR(10)   NOT NULL,
    map_embed_url  VARCHAR(2000) NOT NULL,
    order_index    INT           NOT NULL DEFAULT 0,
    active         BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP     NOT NULL,
    updated_at     TIMESTAMP     NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id),
    CONSTRAINT uq_location_slug UNIQUE (slug)
);

CREATE TABLE hero_slide (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url       VARCHAR(500) NOT NULL,
    delay_seconds   INT           NOT NULL DEFAULT 0,
    order_index     INT           NOT NULL DEFAULT 0,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL,
    CONSTRAINT pk_hero_slide PRIMARY KEY (id)
);
