-- =====================================================================
-- Admin users for the JWT-protected admin panel.
-- The initial admin account is seeded at startup by AdminUserSeeder
-- (BCrypt-hashed), so no password is stored here.
-- =====================================================================

CREATE TABLE admin_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(60)   NOT NULL,
    password    VARCHAR(100)  NOT NULL,
    role        VARCHAR(20)   NOT NULL DEFAULT 'ADMIN',
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP     NOT NULL,
    CONSTRAINT pk_admin_user PRIMARY KEY (id),
    CONSTRAINT uq_admin_user_username UNIQUE (username)
);
