-- =====================================================================
-- Migration V4: Yape/Plin configuration and Burger Ratings for Local AI Ranking
-- =====================================================================

ALTER TABLE site_setting ADD COLUMN IF NOT EXISTS yape_qr_url VARCHAR(500) DEFAULT 'https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=YAPE-LA-BUMANGUESA-989451473';
ALTER TABLE site_setting ADD COLUMN IF NOT EXISTS yape_number VARCHAR(40) DEFAULT '989 451 473';
ALTER TABLE site_setting ADD COLUMN IF NOT EXISTS yape_holder VARCHAR(120) DEFAULT 'La Bumanguesa Ica';

CREATE TABLE IF NOT EXISTS burger_rating (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id     BIGINT                                   NOT NULL,
    stars       INT                                      NOT NULL,
    comment     VARCHAR(500),
    created_at  TIMESTAMP                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_burger_rating PRIMARY KEY (id),
    CONSTRAINT fk_rating_item FOREIGN KEY (item_id) REFERENCES menu_item(id) ON DELETE CASCADE
);

-- Seed initial 5-star ratings for signature burgers
INSERT INTO burger_rating (item_id, stars, comment, created_at)
SELECT id, 5, '¡La mejor hamburguesa de Ica!', CURRENT_TIMESTAMP FROM menu_item WHERE slug IN ('bumanguesa', 'royal', 'queen-cheese', 'american-bacon', 'oklahoma', 'choricarne');
