-- =====================================================================
-- Migration V6: Base de conocimiento del asistente de IA.
--
-- Es la forma correcta de "entrenar" este asistente: en vez de reentrenar
-- los pesos del modelo (que congelaría los datos y exigiría GPU), el negocio
-- escribe aquí los hechos que la IA debe saber. El cambio surte efecto en la
-- siguiente pregunta, sin reiniciar ni reentrenar nada.
-- =====================================================================

CREATE TABLE IF NOT EXISTS ai_knowledge (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    topic       VARCHAR(120)  NOT NULL,
    answer      VARCHAR(1000) NOT NULL,
    order_index INT           NOT NULL DEFAULT 0,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_ai_knowledge PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_ai_knowledge_active_order ON ai_knowledge (active, order_index);

-- Semilla con las preguntas que la IA no sabía responder en las pruebas.
-- Son ejemplos editables: el negocio debe ajustarlos a su realidad.
INSERT INTO ai_knowledge (topic, answer, order_index)
SELECT * FROM (VALUES
    ('Tiempo de delivery',
     'El delivery demora entre 30 y 45 minutos dentro de Ica, según la zona y la carga del momento.',
     1),
    ('Zona de cobertura del delivery',
     'Repartimos en toda la ciudad de Ica. Para distritos alejados, consulta por WhatsApp antes de pedir.',
     2),
    ('Wifi y estacionamiento',
     'En nuestros locales hay wifi para clientes. No contamos con estacionamiento propio.',
     3),
    ('Reservas',
     'No tomamos reservas: la atención en local es por orden de llegada.',
     4),
    ('Opciones vegetarianas',
     'Por ahora todas nuestras hamburguesas llevan carne. Puedes pedir adicionales sin carne como papas, aros de cebolla o nachos.',
     5),
    ('Costo del delivery',
     'El costo del delivery depende de la zona. Te lo confirmamos por WhatsApp al tomar el pedido.',
     6)
) AS seed(topic, answer, order_index)
WHERE NOT EXISTS (SELECT 1 FROM ai_knowledge);
