-- =====================================================================
-- Migration V8: Adicionales ("Arma tu burger") como datos, no como código.
--
-- Estaban duplicados y descuadrados en dos listas hardcodeadas del frontend:
-- la sección de la carta mostraba 24 y el modal de pedido solo permitía pedir
-- 7. Con una única fuente en base de datos, la página, el modal y el asistente
-- de IA ven exactamente lo mismo, y se pueden editar sin tocar código.
-- =====================================================================

CREATE TABLE IF NOT EXISTS menu_extra (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(120)  NOT NULL,
    price       NUMERIC(8, 2) NOT NULL,
    order_index INT           NOT NULL DEFAULT 0,
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_menu_extra PRIMARY KEY (id),
    CONSTRAINT uq_menu_extra_name UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS ix_menu_extra_active_order ON menu_extra (active, order_index);

INSERT INTO menu_extra (name, price, order_index)
SELECT * FROM (VALUES
    ('Carne de Hamburguesa',     8.00,  1),
    ('Carne Deshilachada',       8.00,  2),
    ('Pollo Deshilachado',       8.00,  3),
    ('Filete de Pollo',         10.00,  4),
    ('Costillas de Cerdo',      12.00,  5),
    ('Chicharrón (2 und)',      12.00,  6),
    ('Alitas (3 und)',          12.00,  7),
    ('Baño en Queso Mozarella', 10.00,  8),
    ('Salchicha Ahumada',        6.00,  9),
    ('Aros de Cebolla',          6.00, 10),
    ('Maíz Dulce',               7.00, 11),
    ('Queso Paria',              4.50, 12),
    ('Guacamole',                3.00, 13),
    ('Chorizo',                  3.00, 14),
    ('Tocineta',                 3.00, 15),
    ('Plátano Maduro',           3.00, 16),
    ('Salsa BBQ',                3.00, 17),
    ('Queso Cheddar',            3.00, 18),
    ('Huevo',                    2.00, 19),
    ('Huevo de Codorniz',        2.00, 20),
    ('Jamón',                    1.00, 21),
    ('Porción de Papas',         8.00, 22),
    ('Nachos',                   4.00, 23),
    ('Rodaja de Piña',           3.00, 24)
) AS seed(name, price, order_index)
WHERE NOT EXISTS (SELECT 1 FROM menu_extra);
